### ISSUE TITLE
Is this the repo that causes the error?

### ISSUE THREAD

**Issue by matentzn** [ufbmi/ORCS#1]
This one I mean?

https://github.com/INCATools/ontology-development-kit/issues/491

Right now I cant run

```
sh run.sh make IMP=false orcs.obo
```

Because of an unsatisfiable class.. Are all the up to date files committed?

**Comment by dillerm** [comment]
Yes, this is the one. I will investigate that further.

**Comment by hoganwr** [comment]
I was able to fix the unsatisfiable class but still get the build error.
I'll check in the updated orcs-edit.owl now.

**Comment by matentzn** [comment]
I remember now.. 

IAO and OMRSE use an expression on some classes, see http://purl.obolibrary.org/obo/OMRSE_00000093 (not even ontobee can read this):

![image](https://user-images.githubusercontent.com/7070631/140420376-80628490-747b-4958-b81a-8b67d1fd51b6.png)

which is using inverse(IAO:0000136) directly in a class expression. OBO cannot handle that.

In OMRSE, we created a custom pipeline that first deletes those axioms from the ontology before producing the OBO format:

https://github.com/ufbmi/OMRSE/blob/master/src/ontology/omrse.Makefile#L18

**Comment by dillerm** [comment]
This worked!
